export const QuizData = [
    {
      q: "What is JavaScript?",
      a: "JS is Programming language",
      b: "JS is Framework",
      c: "None",
      d: "Typed Language",
      ans: "JS is Programming language",
    },
    {
      q: "What is ReactJS?",
      a: "Library",
      b: "React is a JavaScript Library",
      c: "Framework",
      d: "Language",
      ans: "React is a JavaScript Library",
    },
    {
      q: "Full Form of JS?",
      a: "JavaSell",
      b: "JavaSpring",
      c: "JavaScript",
      d: "JavaSplit",
      ans: "JavaScript",
    },
    {
      q: "Who Developed JS?",
      a: "Brendon",
      b: "Brendon Mac",
      c: "Bretly",
      d: "Brendon Eich",
      ans: "Brendon Eich",
    },
    {
      q: "Who Developed ReactJS?",
      a: "Jordan Walk",
      b: "Jordan",
      c: "Jordan King",
      d: "Jordan Sen",
      ans: "Jordan Walk",
    },
    {
      q: "What is JSX?",
      a: "JavaScript XML",
      b: "A templating engine",
      c: "A CSS framework",
      d: "A new JavaScript syntax",
      ans: "JavaScript XML",
    },
    {
      q: "What is the purpose of the useEffect hook in React?",
      a: "To manage state",
      b: "To fetch data from an API",
      c: "To handle side effects",
      d: "To update props",
      ans: "To handle side effects",
    },
    {
      q: "What is Redux?",
      a: "A CSS framework",
      b: "A database",
      c: "A state management tool",
      d: "A component library",
      ans: "A state management tool",
    },
    {
      q: "What is Prop Drilling in React?",
      a: "Passing props down multiple components",
      b: "Fetching data from an API",
      c: "Manipulating the DOM directly",
      d: "Managing global state",
      ans: "Passing props down multiple components",
    },
    {
      q: "What does React.memo do?",
      a: "Memoizes the result to avoid re-rendering",
      b: "Manages state globally",
      c: "Handles DOM manipulations",
      d: "Fetches data from APIs",
      ans: "Memoizes the result to avoid re-rendering",
    },
    {
      q: "What is the virtual DOM?",
      a: "A lightweight copy of the actual DOM",
      b: "A real DOM manipulation method",
      c: "A JavaScript framework",
      d: "A new HTML specification",
      ans: "A lightweight copy of the actual DOM",
    },
    {
      q: "What is the difference between state and props?",
      a: "State is mutable, props are immutable",
      b: "Props can only be updated in child components",
      c: "State can be passed to child components",
      d: "Both state and props are mutable",
      ans: "State is mutable, props are immutable",
    },
    {
      q: "How can you optimize React performance?",
      a: "By using React.memo",
      b: "By avoiding hooks",
      c: "By using more components",
      d: "By removing keys from lists",
      ans: "By using React.memo",
    },
    {
      q: "How do you handle forms in React?",
      a: "Using controlled components",
      b: "Using state variables only",
      c: "By writing HTML only",
      d: "By avoiding event listeners",
      ans: "Using controlled components",
    },
    {
      q: "What is the use of useContext hook in React?",
      a: "To consume context data without prop drilling",
      b: "To manage lifecycle methods",
      c: "To fetch data from an API",
      d: "To handle state updates",
      ans: "To consume context data without prop drilling",
    },
  ];
  